# Generated by Django 4.1.2 on 2022-12-02 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_transaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.AddField(
            model_name="order",
            name="product",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="app.product"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Card", "Card"), ("Cash", "Cash")], max_length=200, null=True
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("Cheese Pizza", "Cheese Pizza"),
                    ("Pepperoni Pizza", "Pepperoni Pizza"),
                    ("Sausage Pizza", "Sausage Pizza"),
                    ("Meat Lover Pizza", "Meat Lover Pizza"),
                    ("Hawaiian Pizza", "Hawaiian Pizza"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
