# Generated by Django 4.1.2 on 2022-12-02 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_remove_product_desc_remove_product_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="status",
            new_name="payment",
        ),
    ]
